# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\ELMOIV\Desktop\Python Data\elmocut\exe\ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(870, 560)
        MainWindow.setMinimumSize(QtCore.QSize(870, 560))
        MainWindow.setToolTip("")
        MainWindow.setAnimated(True)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(100, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.lblcenter = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Menlo" if __import__('sys').platform == 'darwin' else "Consolas")
        font.setPointSize(9)
        self.lblcenter.setFont(font)
        self.lblcenter.setText("")
        self.lblcenter.setAlignment(QtCore.Qt.AlignCenter)
        self.lblcenter.setObjectName("lblcenter")
        self.gridLayout.addWidget(self.lblcenter, 3, 3, 1, 2)
        self.btnSettings = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSettings.sizePolicy().hasHeightForWidth())
        self.btnSettings.setSizePolicy(sizePolicy)
        self.btnSettings.setMinimumSize(QtCore.QSize(0, 50))
        self.btnSettings.setText("")
        self.btnSettings.setIconSize(QtCore.QSize(40, 40))
        self.btnSettings.setObjectName("btnSettings")
        self.gridLayout.addWidget(self.btnSettings, 0, 5, 2, 1)
        self.btnScanHard = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnScanHard.sizePolicy().hasHeightForWidth())
        self.btnScanHard.setSizePolicy(sizePolicy)
        self.btnScanHard.setMinimumSize(QtCore.QSize(0, 50))
        self.btnScanHard.setText("")
        self.btnScanHard.setIconSize(QtCore.QSize(40, 40))
        self.btnScanHard.setObjectName("btnScanHard")
        self.gridLayout.addWidget(self.btnScanHard, 0, 2, 2, 1)
        self.pgbar = QtWidgets.QProgressBar(self.centralwidget)
        self.pgbar.setMinimumSize(QtCore.QSize(0, 25))
        self.pgbar.setProperty("value", 0)
        self.pgbar.setTextVisible(False)
        self.pgbar.setObjectName("pgbar")
        self.gridLayout.addWidget(self.pgbar, 4, 1, 1, 8)
        self.btnKillAll = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnKillAll.sizePolicy().hasHeightForWidth())
        self.btnKillAll.setSizePolicy(sizePolicy)
        self.btnKillAll.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnKillAll.setFont(font)
        self.btnKillAll.setText("")
        self.btnKillAll.setIconSize(QtCore.QSize(40, 40))
        self.btnKillAll.setObjectName("btnKillAll")
        self.gridLayout.addWidget(self.btnKillAll, 0, 3, 2, 1)
        self.lblDonate = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblDonate.setFont(font)
        self.lblDonate.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lblDonate.setText("")
        self.lblDonate.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblDonate.setObjectName("lblDonate")
        self.gridLayout.addWidget(self.lblDonate, 3, 5, 1, 2)
        self.btnScanEasy = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnScanEasy.sizePolicy().hasHeightForWidth())
        self.btnScanEasy.setSizePolicy(sizePolicy)
        self.btnScanEasy.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnScanEasy.setFont(font)
        self.btnScanEasy.setText("")
        self.btnScanEasy.setIconSize(QtCore.QSize(40, 40))
        self.btnScanEasy.setObjectName("btnScanEasy")
        self.gridLayout.addWidget(self.btnScanEasy, 0, 1, 2, 1)
        self.lblleft = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblleft.sizePolicy().hasHeightForWidth())
        self.lblleft.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Menlo" if __import__('sys').platform == 'darwin' else "Consolas")
        font.setPointSize(10)
        self.lblleft.setFont(font)
        self.lblleft.setObjectName("lblleft")
        self.gridLayout.addWidget(self.lblleft, 3, 1, 1, 2)
        self.btnUnkillAll = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnUnkillAll.sizePolicy().hasHeightForWidth())
        self.btnUnkillAll.setSizePolicy(sizePolicy)
        self.btnUnkillAll.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnUnkillAll.setFont(font)
        self.btnUnkillAll.setText("")
        self.btnUnkillAll.setIconSize(QtCore.QSize(40, 40))
        self.btnUnkillAll.setObjectName("btnUnkillAll")
        self.gridLayout.addWidget(self.btnUnkillAll, 0, 4, 2, 1)
        self.lblright = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblright.sizePolicy().hasHeightForWidth())
        self.lblright.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Menlo" if __import__('sys').platform == 'darwin' else "Consolas")
        font.setPointSize(10)
        self.lblright.setFont(font)
        self.lblright.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblright.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblright.setObjectName("lblright")
        self.gridLayout.addWidget(self.lblright, 3, 7, 1, 2)
        self.btnAbout = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAbout.sizePolicy().hasHeightForWidth())
        self.btnAbout.setSizePolicy(sizePolicy)
        self.btnAbout.setMinimumSize(QtCore.QSize(0, 50))
        self.btnAbout.setText("")
        self.btnAbout.setIconSize(QtCore.QSize(40, 40))
        self.btnAbout.setObjectName("btnAbout")
        self.gridLayout.addWidget(self.btnAbout, 0, 6, 2, 1)
        self.tableScan = QtWidgets.QTableWidget(self.centralwidget)
        self.tableScan.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableScan.sizePolicy().hasHeightForWidth())
        self.tableScan.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Menlo" if __import__('sys').platform == 'darwin' else "Consolas")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.tableScan.setFont(font)
        self.tableScan.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableScan.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableScan.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableScan.setTabKeyNavigation(False)
        self.tableScan.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableScan.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableScan.setTextElideMode(QtCore.Qt.ElideNone)
        self.tableScan.setShowGrid(False)
        self.tableScan.setGridStyle(QtCore.Qt.NoPen)
        self.tableScan.setWordWrap(False)
        self.tableScan.setObjectName("tableScan")
        self.tableScan.setColumnCount(0)
        self.tableScan.setRowCount(0)
        self.tableScan.horizontalHeader().setVisible(True)
        self.tableScan.horizontalHeader().setDefaultSectionSize(170)
        self.tableScan.horizontalHeader().setMinimumSectionSize(170)
        self.tableScan.horizontalHeader().setStretchLastSection(False)
        self.tableScan.verticalHeader().setVisible(True)
        self.tableScan.verticalHeader().setMinimumSectionSize(28)
        self.gridLayout.addWidget(self.tableScan, 2, 1, 1, 8)
        self.horizontalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ZubCut"))
        self.btnScanEasy.setShortcut(_translate("MainWindow", "Space"))
        self.lblleft.setText(_translate("MainWindow", "IDLE"))
        self.lblright.setText(_translate("MainWindow", "0 devices"))
        self.tableScan.setSortingEnabled(False)
