from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Traffic(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("TrafficWindow")
        MainWindow.resize(700, 420)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.lblVictim = QtWidgets.QLabel(self.centralwidget)
        self.lblVictim.setAlignment(QtCore.Qt.AlignCenter)
        self.verticalLayout.addWidget(self.lblVictim)
        self.lblMode = QtWidgets.QLabel(self.centralwidget)
        self.lblMode.setAlignment(QtCore.Qt.AlignCenter)
        self.verticalLayout.addWidget(self.lblMode)
        self.table = QtWidgets.QTableWidget(self.centralwidget)
        self.table.setColumnCount(5)
        self.table.setHorizontalHeaderLabels(["Destination", "Port", "Proto", "Packets", "Bytes"])
        self.table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table.verticalHeader().setVisible(False)
        self.table.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.table)
        # Patterns table
        self.patterns = QtWidgets.QTableWidget(self.centralwidget)
        self.patterns.setColumnCount(4)
        self.patterns.setHorizontalHeaderLabels(["Proto", "Port", "LenBucket", "Packets"])
        self.patterns.verticalHeader().setVisible(False)
        self.patterns.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.patterns)
        # Pattern samples table
        self.pattern_samples = QtWidgets.QTableWidget(self.centralwidget)
        self.pattern_samples.setColumnCount(4)
        self.pattern_samples.setHorizontalHeaderLabels(["Time", "Peer", "Len", "Preview (hex)"])
        self.pattern_samples.verticalHeader().setVisible(False)
        self.pattern_samples.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.pattern_samples)
        self.buttons = QtWidgets.QHBoxLayout()
        self.chkIncludePort = QtWidgets.QCheckBox("Match Port")
        self.btnBlock = QtWidgets.QPushButton("Block Selected")
        self.btnUnblock = QtWidgets.QPushButton("Unblock Selected")
        self.btnExport = QtWidgets.QPushButton("Export Rules")
        self.btnImport = QtWidgets.QPushButton("Import Rules")
        self.btnPFTest = QtWidgets.QPushButton("Test PF")
        self.chkForward = QtWidgets.QCheckBox("Forward Mode")
        self.buttons.addWidget(self.chkIncludePort)
        self.buttons.addWidget(self.btnBlock)
        self.buttons.addWidget(self.btnUnblock)
        self.buttons.addWidget(self.btnExport)
        self.buttons.addWidget(self.btnImport)
        self.buttons.addWidget(self.btnPFTest)
        self.buttons.addWidget(self.chkForward)
        self.btnBlockPattern = QtWidgets.QPushButton("Block This Type")
        self.btnUnblockPattern = QtWidgets.QPushButton("Unblock This Type")
        self.buttons.addWidget(self.btnBlockPattern)
        self.buttons.addWidget(self.btnUnblockPattern)
        self.verticalLayout.addLayout(self.buttons)

        # Packet preview
        self.preview = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.preview.setReadOnly(True)
        self.verticalLayout.addWidget(self.preview)
        MainWindow.setCentralWidget(self.centralwidget)


